### ISSUE TITLE
whois analyzer needs proxy support

### ISSUE THREAD

**Issue by seanmcfeely** [ace-ecosystem/ACE#65]
I turned this module on to test it but found that it needs proxy support so saq.PROXIES (or [future replacement](https://github.com/ace-ecosystem/ACE/issues/63)) can be passed to it if a proxy config item is set for the module.

```
[ERROR] analysis module WhoisAnalyzer failed on WorkTarget(obs:url(http://stupid-bad-domain.example.com/malware/cats),analyis:None,module:None,dep:None) for RootAnalysis(9d163c27-96fb-4720-969f-67dfca12f792) reason timed out
```

**Comment by krayzpipes** [comment]
So I dug into this more deeply because I had a poor understanding of how `whois` actually worked at the protocol level.

- When given an F_URL observable, the underlying `python-whois` library strips the domain out of the URL and sends a whois request over TCP 43--because `whois` is its own protocol apparently.  It doesn't use HTTP/S as the transport (see references at the bottom for an example)
    1. It first tries to run a subprocess calling `whois` on your OS. If that's not there:
    2. Uses a socket to manually make the connection out.
- Unfortunately, using the HTTP proxy won't help in this case, but you have a couple options:
    - Open a firewall/security-group rule allowing outbound TCP 43.
    - The python-whois library is compatible with a SOCKS proxy -- which doesn't care about the application layer you're running through it... it just sets up and tears down TCP connections for you. For example, if your ACE box does not have a route to the internet (or an internet gateway/NAT gateway), then you will likely need a SOCKS proxy setup in a location similar to where you would put your HTTP proxy. I have not used a SOCKS proxy before, so this was neat to read about.

References:
- Whois protocol example: https://tools.ietf.org/html/rfc3912#section-2
- python-whois order of `whois` library:  https://github.com/richardpenman/pywhois/blob/b9cf01fccef9bc5bbfd7b2ae6d4d37699a70bf78/whois/__init__.py#L36
- SOCKS proxy (page 6 has a nice diagram-- I like visuals): https://www.giac.org/paper/gsec/2326/understanding-implementing-socks-server-guide-set-socks-environment/104018

**Comment by krayzpipes** [comment]
Let me know what you think and if this is okay to close out. @seanmcfeely

**Comment by seanmcfeely** [comment]
Hey @krayzpipes yes we can for sure close this. Also, I did configure a socks proxy and confirm it works with a SOCKS environment variable defined. That could be made configurable but I don't know of any other ace code that would be impacted by having that env set globally all the time.
Also, as an aside, I was thinking this module could also benefit with a configurable detection point to be made if whois reveals the domain was last updated within X days.
